---
- name: Add line to bashrc
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    insertafter: EOF
    marker: "# insert by ansible"
    content: |
      SESSION_NAME=ope

      if [[ -z "$TMUX" && -z "$STY" ]] && type tmux >/dev/null 2>&1; then
        option=""
        if tmux has-session -t ${SESSION_NAME}; then
          option="-2 attach -t ${SESSION_NAME}"
        else
          option="-2 new -s ${SESSION_NAME}"
        fi  
        # tmux $option && exit
        tmux $option 
      fi

      function ssh() {
        # tmux起動時
        trap "tmux select-pane -P 'bg=default'" INT EXIT TERM
        if [[ -n $(printenv TMUX) ]] ; then
            # 現在のペインIDを記録
            local pane_id=$(tmux display -p '#{pane_id}')
            # 接続先ホスト名に応じて背景色を切り替え
            tmux select-pane -P 'bg=#04376F'

            # 通常通りssh続行
            command ssh $@

            # デフォルトの背景色に戻す
            tmux select-pane -t $pane_id -P 'default'
        else
            command ssh $@
        fi
      }
      #----
      function parse_git_branch {
          git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ [\1]/'
      }
      function promps {
          local  BLUE="\[\e[1;34m\]"
          local  RED="\[\e[1;31m\]"
          local  GREEN="\[\e[1;32m\]"
          local  YELLOW="\[\e[1;33m\]"
          local  WHITE="\[\e[00m\]"
          local  GRAY="\[\e[1;37m\]"

          case $TERM in
              xterm*) TITLEBAR='\[\e]0;\W\007\]';;
              *)      TITLEBAR="";;
          esac
          local BASE="\u@\h"
          PS1="${TITLEBAR}${GREEN}${BASE}${WHITE}:${BLUE}\w${RED}\$(parse_git_branch)${BLUE}\$${WHITE} \n"
      }
      promps
      export FZF_DEFAULT_OPTS='--height 40% --reverse --border'
      export FZF_CTRL_T_COMMAND='fd -t f --hidden --follow -d 5 -E .git'
      export FZF_CTRL_T_OPTS='--preview \"bat  --color=always --style=header,grid --line-range :100 {}\"'
      #----
