---
  # apt install
- name: Add apt repository
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ apt_repositories }}"
  become: yes

- name: Update apt and install softwares
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ apt_packages }}"
  become: yes
