---
# tasks file for ubuntu

# Check directory
- name: Check the git directory status
  stat:
    path: "{{ item.dest }}"
  with_items: "{{ git_repos }}"
  register: git_repos_directory
    
- name: Check the ssh status
  stat:
    path: "~/.ssh/id_rsa"
  register: id_rsa_file

- name: Create directory for local development
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
  with_items: "{{ dev_directories }}"

- import_tasks: apt-install.yml
- import_tasks: dev-install.yml
- import_tasks: add-bashrc-lines.yml

 # dotfiles setup
- name: Setup dotfiles
  shell:
    cmd: cd ~/workspace/dotfiles; bash setup.sh
