# https://github.com/strawlab/strawlab-ansible-roles/blob/master/.github/workflows/build.yml
name: build

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    # TODO secretの共有方法
    steps:
    - uses: actions/checkout@v2
    # - uses: webfactory/ssh-agent@v0.4.1
      # with:
        # ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # - name: Install sudo package
      # run: apt update && apt install sudo
    - name: Install ansible
      run: sudo apt-get install ansible
    - name: Install collections with a requirements file
      run: ansible-galaxy collection install -r collections/requirements.yml
    - name: Install roles with a requirements file
      run: ansible-galaxy install -r roles/requirements.yml
    - name: Build
      run: ansible-playbook -i "localhost," -c local playbook.yml -vault-password-file ~/vault_pass
